version: '3.2'

services:
  memcached:
    image: memcached:1.5-alpine
    ports:
      - "11211:11211"
    restart: always
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "forge"
    ports:
      - "3306:3306"
    restart: always
  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
    restart: always
  app:
# Temporary build
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: royalcms/royalcms-framework-app:latest
    environment:
      PS1: '\[\033[1;32m\]\[\033[1;36m\][\u@docker] \[\033[1;34m\]\w\[\033[0;35m\] \[\033[1;36m\]# \[\033[0m\]'
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - .:/src:cached
      - composer-data:/tmp/composer:cached

volumes:
  composer-data: