version: '3'
services:
  memcached:
    image: memcached:1.5-alpine
    ports:
      - "11211:11211"
    restart: always
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "forge"
    ports:
      - "3306:3306"
    restart: always
  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
    restart: always