<?php

$basePath = $royalcms['path.base'];

return [

    $basePath.'/vendor/symfony/debug/ExceptionHandler.php',
    $basePath.'/vendor/symfony/debug/ErrorHandler.php',
    $basePath.'/vendor/symfony/http-foundation/Request.php',
    $basePath.'/vendor/symfony/http-foundation/Response.php',
    $basePath.'/vendor/symfony/http-foundation/ParameterBag.php',
    $basePath.'/vendor/symfony/http-foundation/FileBag.php',
    $basePath.'/vendor/symfony/http-foundation/ServerBag.php',
    $basePath.'/vendor/symfony/http-foundation/HeaderBag.php',
    $basePath.'/vendor/symfony/http-foundation/Session/SessionInterface.php',
    $basePath.'/vendor/symfony/http-foundation/Session/SessionBagInterface.php',
    $basePath.'/vendor/symfony/http-foundation/Session/Attribute/AttributeBagInterface.php',
    $basePath.'/vendor/symfony/http-foundation/Session/Attribute/AttributeBag.php',
    $basePath.'/vendor/symfony/http-foundation/Session/Storage/MetadataBag.php',
    $basePath.'/vendor/symfony/http-foundation/Session/Storage/Handler/AbstractSessionHandler.php',
    $basePath.'/vendor/symfony/http-foundation/Session/Storage/Handler/NullSessionHandler.php',
    $basePath.'/vendor/symfony/http-foundation/AcceptHeaderItem.php',
    $basePath.'/vendor/symfony/http-foundation/AcceptHeader.php',
    $basePath.'/vendor/symfony/http-foundation/ResponseHeaderBag.php',
    $basePath.'/vendor/symfony/http-foundation/Cookie.php',
    $basePath.'/vendor/symfony/http-kernel/HttpKernelInterface.php',
    $basePath.'/vendor/symfony/http-kernel/TerminableInterface.php',
    $basePath.'/vendor/symfony/routing/CompiledRoute.php',
    $basePath.'/vendor/symfony/routing/RouteCompilerInterface.php',
    $basePath.'/vendor/symfony/routing/RouteCompiler.php',
    $basePath.'/vendor/symfony/routing/Route.php',
    $basePath.'/vendor/symfony/finder/SplFileInfo.php',
    $basePath.'/vendor/symfony/finder/Expression/Glob.php',
    $basePath.'/vendor/symfony/finder/Expression/Regex.php',
    $basePath.'/vendor/symfony/finder/Expression/ValueInterface.php',
    $basePath.'/vendor/symfony/finder/Expression/Expression.php',
    $basePath.'/vendor/symfony/finder/Iterator/FilterIterator.php',
    $basePath.'/vendor/symfony/finder/Iterator/MultiplePcreFilterIterator.php',
    $basePath.'/vendor/symfony/finder/Iterator/PathFilterIterator.php',
    $basePath.'/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php',
    $basePath.'/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php',
    $basePath.'/vendor/symfony/finder/Iterator/FileTypeFilterIterator.php',
    $basePath.'/vendor/symfony/finder/Iterator/FilenameFilterIterator.php',
    $basePath.'/vendor/symfony/finder/Shell/Shell.php',
    $basePath.'/vendor/symfony/finder/Adapter/AdapterInterface.php',
    $basePath.'/vendor/symfony/finder/Adapter/AbstractAdapter.php',
    $basePath.'/vendor/symfony/finder/Adapter/AbstractFindAdapter.php',
    $basePath.'/vendor/symfony/finder/Adapter/GnuFindAdapter.php',
    $basePath.'/vendor/symfony/finder/Adapter/PhpAdapter.php',
    $basePath.'/vendor/symfony/finder/Adapter/BsdFindAdapter.php',
    $basePath.'/vendor/symfony/finder/Finder.php',
    $basePath.'/vendor/symfony/finder/Glob.php',
    $basePath.'/vendor/symfony/finder/Iterator/DepthRangeFilterIterator.php',
    $basePath.'/vendor/symfony/finder/Comparator/Comparator.php',
    $basePath.'/vendor/symfony/finder/Comparator/NumberComparator.php',
    $basePath.'/vendor/symfony/translation-contracts/LocaleAwareInterface.php',
    $basePath.'/vendor/symfony/translation/TranslatorInterface.php',
    $basePath.'/vendor/symfony/console/Command/Command.php',
    $basePath.'/vendor/symfony/var-dumper/Cloner/ClonerInterface.php',
    $basePath.'/vendor/symfony/var-dumper/Cloner/AbstractCloner.php',
    $basePath.'/vendor/symfony/var-dumper/Cloner/VarCloner.php',

    $basePath.'/vendor/nesbot/carbon/src/Carbon/CarbonInterface.php',
    $basePath.'/vendor/nesbot/carbon/src/Carbon/Traits/Week.php',
    $basePath.'/vendor/nesbot/carbon/src/Carbon/Traits/Units.php',
    $basePath.'/vendor/nesbot/carbon/src/Carbon/Traits/Timestamp.php',
    $basePath.'/vendor/nesbot/carbon/src/Carbon/Traits/Test.php',
    $basePath.'/vendor/nesbot/carbon/src/Carbon/Traits/Serialization.php',
    $basePath.'/vendor/nesbot/carbon/src/Carbon/Traits/Rounding.php',
    $basePath.'/vendor/nesbot/carbon/src/Carbon/Traits/Localization.php',
    $basePath.'/vendor/nesbot/carbon/src/Carbon/Traits/Options.php',
    $basePath.'/vendor/nesbot/carbon/src/Carbon/Traits/Cast.php',
    $basePath.'/vendor/nesbot/carbon/src/Carbon/Traits/Mutability.php',
    $basePath.'/vendor/nesbot/carbon/src/Carbon/Traits/Modifiers.php',
    $basePath.'/vendor/nesbot/carbon/src/Carbon/Traits/Mixin.php',
    $basePath.'/vendor/nesbot/carbon/src/Carbon/Traits/Macro.php',
    $basePath.'/vendor/nesbot/carbon/src/Carbon/Traits/Difference.php',
    $basePath.'/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php',
    $basePath.'/vendor/nesbot/carbon/src/Carbon/Traits/Converter.php',
    $basePath.'/vendor/nesbot/carbon/src/Carbon/Traits/Comparison.php',
    $basePath.'/vendor/nesbot/carbon/src/Carbon/Traits/Boundaries.php',
    $basePath.'/vendor/nesbot/carbon/src/Carbon/Traits/Date.php',
    $basePath.'/vendor/nesbot/carbon/src/Carbon/Carbon.php',

    $basePath.'/vendor/vlucas/phpdotenv/src/Environment/Adapter/AdapterInterface.php',
    $basePath.'/vendor/vlucas/phpdotenv/src/Environment/VariablesInterface.php',
    $basePath.'/vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php',
    $basePath.'/vendor/vlucas/phpdotenv/src/Environment/DotenvVariables.php',
    $basePath.'/vendor/vlucas/phpdotenv/src/Environment/FactoryInterface.php',
    $basePath.'/vendor/vlucas/phpdotenv/src/Environment/DotenvFactory.php',
    $basePath.'/vendor/vlucas/phpdotenv/src/Environment/Adapter/ArrayAdapter.php',
    $basePath.'/vendor/vlucas/phpdotenv/src/Environment/Adapter/PutenvAdapter.php',
    $basePath.'/vendor/vlucas/phpdotenv/src/Environment/Adapter/ServerConstAdapter.php',
    $basePath.'/vendor/vlucas/phpdotenv/src/Environment/Adapter/EnvConstAdapter.php',

    $basePath.'/vendor/league/flysystem/src/ReadInterface.php',
    $basePath.'/vendor/league/flysystem/src/AdapterInterface.php',
    $basePath.'/vendor/league/flysystem/src/FilesystemInterface.php',
    $basePath.'/vendor/league/flysystem/src/ConfigAwareTrait.php',
    $basePath.'/vendor/league/flysystem/src/Plugin/PluggableTrait.php',
    $basePath.'/vendor/league/flysystem/src/Adapter/AbstractAdapter.php',
    $basePath.'/vendor/league/flysystem/src/Adapter/Local.php',
    $basePath.'/vendor/league/flysystem/src/Filesystem.php',

    $basePath.'/vendor/psr/container/src/ContainerInterface.php',
    $basePath.'/vendor/psr/simple-cache/src/CacheInterface.php',
    $basePath.'/vendor/psr/log/Psr/Log/LoggerInterface.php',

    $basePath.'/vendor/filp/whoops/src/Whoops/Handler/HandlerInterface.php',
    $basePath.'/vendor/filp/whoops/src/Whoops/Handler/Handler.php',
    $basePath.'/vendor/filp/whoops/src/Whoops/Handler/PrettyPageHandler.php',
    $basePath.'/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php',
    $basePath.'/vendor/filp/whoops/src/Whoops/Util/SystemFacade.php',
    $basePath.'/vendor/filp/whoops/src/Whoops/RunInterface.php',
    $basePath.'/vendor/filp/whoops/src/Whoops/Run.php',

    $basePath.'/vendor/phpoption/phpoption/src/PhpOption/Option.php',
    $basePath.'/vendor/phpoption/phpoption/src/PhpOption/None.php',

    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/AddressEncoder.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/AddressEncoder/IdnAddressEncoder.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Events/EventDispatcher.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Events/SimpleEventDispatcher.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/OutputByteStream.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/InputByteStream.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Preferences.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/Auth/XOAuth2Authenticator.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/Auth/NTLMAuthenticator.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/Auth/PlainAuthenticator.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/Auth/LoginAuthenticator.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/Authenticator.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/Auth/CramMd5Authenticator.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpHandler.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/IoBuffer.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ReplacementFilterFactory.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/StreamFilters/StringReplacementFilterFactory.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Filterable.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/AbstractFilterableInputStream.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/SmtpAgent.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/SmtpTransport.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/DependencyContainer.php',
    $basePath.'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php',

    $basePath.'/vendor/sentry/sentry/lib/Raven/Stacktrace.php',
    $basePath.'/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php',
    $basePath.'/vendor/sentry/sentry/lib/Raven/TransactionStack.php',
    $basePath.'/vendor/sentry/sentry/lib/Raven/ReprSerializer.php',
    $basePath.'/vendor/sentry/sentry/lib/Raven/Serializer.php',
    $basePath.'/vendor/sentry/sentry/lib/Raven/Breadcrumbs.php',
    $basePath.'/vendor/sentry/sentry/lib/Raven/Context.php',
    $basePath.'/vendor/sentry/sentry/lib/Raven/Processor.php',
    $basePath.'/vendor/sentry/sentry/lib/Raven/Processor/SanitizeDataProcessor.php',
    $basePath.'/vendor/sentry/sentry/lib/Raven/Compat.php',
    $basePath.'/vendor/sentry/sentry/lib/Raven/Util.php',
    $basePath.'/vendor/sentry/sentry/lib/Raven/Client.php',
//    $basePath.'',


    $basePath.'/vendor/monolog/monolog/src/Monolog/DateTimeImmutable.php',
    $basePath.'/vendor/monolog/monolog/src/Monolog/Formatter/FormatterInterface.php',
    $basePath.'/vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php',
    $basePath.'/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php',
    $basePath.'/vendor/monolog/monolog/src/Monolog/Handler/FormattableHandlerInterface.php',
    $basePath.'/vendor/monolog/monolog/src/Monolog/Handler/ProcessableHandlerInterface.php',
    $basePath.'/vendor/monolog/monolog/src/Monolog/Handler/FormattableHandlerTrait.php',
    $basePath.'/vendor/monolog/monolog/src/Monolog/Handler/ProcessableHandlerTrait.php',
    $basePath.'/vendor/monolog/monolog/src/Monolog/Handler/HandlerInterface.php',
    $basePath.'/vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php',
    $basePath.'/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php',
    $basePath.'/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php',
    $basePath.'/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php',
    $basePath.'/vendor/monolog/monolog/src/Monolog/Handler/Handler.php',
    $basePath.'/vendor/monolog/monolog/src/Monolog/ResettableInterface.php',
    $basePath.'/vendor/monolog/monolog/src/Monolog/Logger.php',

//    $basePath.'/vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php',
//    $basePath.'/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php',
//    $basePath.'/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php',
//    $basePath.'/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php',
//    $basePath.'/vendor/monolog/monolog/src/Monolog/Handler/HandlerInterface.php',
//    $basePath.'/vendor/monolog/monolog/src/Monolog/Formatter/FormatterInterface.php',
//    $basePath.'/vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php',
//    $basePath.'/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php',



    //laravel
    $basePath.'/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Support/Env.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Support/Arr.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Events/Dispatcher.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Http/Kernel.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Cache/Events/KeyWritten.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Filesystem/FileNotFoundException.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectorInterface.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/MySqlProcessor.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/Grammar.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/MySqlGrammar.php',
    $basePath.'/vendor/royalcms/framework/Royalcms/Component/Database/Query/Grammars/MySqlGrammar.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/ConnectionInterface.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/DetectsLostConnections.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/DetectsConcurrencyErrors.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/Connection.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Support/ConfigurationUrlParser.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Routing/Contracts/ControllerDispatcher.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php',
    $basePath.'/vendor/royalcms/framework/Royalcms/Component/Routing/ControllerDispatcher.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Routing/SortedMiddleware.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Routing/Events/RouteMatched.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Routing/RouteParameterBinder.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Routing/Matching/HostValidator.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Routing/Matching/SchemeValidator.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Routing/Matching/MethodValidator.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Routing/Matching/ValidatorInterface.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Routing/Matching/UriValidator.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Routing/RouteCompiler.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Pipeline/Pipeline.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Cache/Events/CacheHit.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Support/Carbon.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Cache/Repository.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Cache/Factory.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Cache/CacheServiceProvider.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Log/ParsesLogConfiguration.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Log/LogManager.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/ConnectionResolverInterface.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Queue/Monitor.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Queue/Factory.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Queue/QueueServiceProvider.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Mail/TransportManager.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Mail/MailQueue.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Mail/Mailer.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Mail/MailServiceProvider.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Translation/Translator.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Translation/Translator.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Translation/Loader.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Translation/FileLoader.php',
    $basePath.'/vendor/royalcms/framework/Royalcms/Component/Translation/FileLoader.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Routing/UrlGenerator.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Support/InteractsWithTime.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Routing/Redirector.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/View/Engines/EngineResolver.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Routing/ResponseFactory.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Console/Application.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Console/Application.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Support/DeferrableProvider.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/MigrationServiceProvider.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Support/AggregateServiceProvider.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Notifications/NotificationServiceProvider.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Pagination/Paginator.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Support/Htmlable.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Pagination/AbstractPaginator.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Pagination/Paginator.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Pagination/PaginationServiceProvider.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Cookie/CookieServiceProvider.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/DatabaseServiceProvider.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Support/Str.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Config/Repository.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Foundation/EnvironmentDetector.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithFlashData.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithContentTypes.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Http/Request.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Routing/Registrar.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Routing/BindingRegistrar.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Routing/Router.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemServiceProvider.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Log/LogServiceProvider.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Routing/Controller.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Routing/UrlRoutable.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Queue/QueueableEntity.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HidesAttributes.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasTimestamps.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasGlobalScopes.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Filesystem/Factory.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Filesystem/Filesystem.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Filesystem/Cloud.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/View/Engine.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/View/ViewFinderInterface.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/View/Factory.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesTranslations.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesStacks.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesLoops.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesLayouts.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesEvents.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesComponents.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/View/Factory.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Redis/Factory.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Session/Session.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Session/Store.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Support/NamespacedItemResolver.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Support/Manager.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Support/DeferrableProvider.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Routing/Matching/ValidatorInterface.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Support/Jsonable.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Support/Arrayable.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Support/Enumerable.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Support/Collection.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/ConnectionInterface.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Database/Connection.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Cache/Events/CacheEvent.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Http/Kernel.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Events/Dispatcher.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Foundation/Application.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Container/Container.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Container/Container.php',







//    $basePath.'',
//    $basePath.'',
//    $basePath.'',



    $basePath.'/vendor/royalcms/container/Royalcms/Component/Container/Container.php',

    //contracts
    $basePath.'/vendor/royalcms/app/Royalcms/Component/App/Contracts/BundlePackage.php',
    $basePath.'/vendor/royalcms/framework/Royalcms/Component/Contracts/Foundation/Royalcms.php',
    $basePath.'/vendor/royalcms/framework/Royalcms/Component/Contracts/Container/Container.php',
    $basePath.'/vendor/royalcms/framework/Royalcms/Component/Contracts/Events/Dispatcher.php',
    $basePath.'/vendor/royalcms/framework/Royalcms/Component/Contracts/ContractsServiceProvider.php',
    $basePath.'/vendor/royalcms/framework/Royalcms/Component/Contracts/Http/Kernel.php',
    $basePath.'/vendor/royalcms/framework/Royalcms/Component/Contracts/Routing/ResponseFactory.php',
//    $basePath.'',
//    $basePath.'',


//    //http
//    $basePath.'/vendor/royalcms/http/Royalcms/Component/Http/Request.php',
//    $basePath.'/vendor/royalcms/http/Royalcms/Component/Http/Middleware/FrameGuard.php',
//    $basePath.'/vendor/royalcms/http/Royalcms/Component/Http/ResponseTrait.php',
//    $basePath.'/vendor/royalcms/http/Royalcms/Component/Http/Response.php',

    //foundation
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Royalcms.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/EnvironmentDetector.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Bootstrap/ConfigureLogging.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Bootstrap/HandleExceptions.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Bootstrap/RegisterFacades.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Bootstrap/RegisterProviders.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Bootstrap/BootProviders.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Bootstrap/LoadConfiguration.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Bootstrap/DetectEnvironment.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Bootstrap/RegisterNamespaces.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Bootstrap/Booted.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Bootstrap/Starting.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Http/Kernel.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Auth/AuthenticatesUsers.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Auth/RedirectsUsers.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Auth/RegistersUsers.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Auth/ResetsPasswords.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Auth/Access/AuthorizesRequests.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Http/Middleware/VerifyCsrfToken.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Http/Middleware/CheckForMaintenanceMode.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Http/FormRequest.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Bus/DispatchesJobs.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Validation/ValidatesRequests.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Providers/FoundationServiceProvider.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Providers/FormRequestServiceProvider.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Support/Providers/AuthServiceProvider.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Support/Providers/RouteServiceProvider.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/Support/Providers/EventServiceProvider.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/AliasLoader.php',
    $basePath.'/vendor/royalcms/foundation/Royalcms/Component/Foundation/ProviderRepository.php',
//
//    $basePath.'/vendor/royalcms/url/Royalcms/Component/Url/Facades/Uri.php',
//    $basePath.'/vendor/royalcms/theme/Royalcms/Component/Theme/Facades/Theme.php',
//    $basePath.'/vendor/royalcms/plugin/Royalcms/Component/Plugin/Facades/Plugin.php',

//    //support
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/ServiceProvider.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/AggregateServiceProvider.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/Traits/Macroable.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/Arr.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/Str.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/NamespacedItemResolver.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/Manager.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/Collection.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/ViewErrorBag.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/MessageBag.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/ArrayHelperTrait.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/StrHelperTrait.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/Format.php',

//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/Facades/Facade.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/Facades/Royalcms.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/Facades/Route.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/Facades/View.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/Facades/Log.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/Facades/DB.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/Facades/Request.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/Facades/Response.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/Facades/Config.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/Facades/Session.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/Facades/Lang.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/Facades/Cache.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/Facades/Event.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/Facades/File.php',
//    $basePath.'/vendor/royalcms/support/Royalcms/Component/Support/Facades/Logger.php',

//    $basePath.'/vendor/royalcms/validation/Royalcms/Component/Validation/ValidationServiceProvider.php',
//    $basePath.'/vendor/royalcms/validation/Royalcms/Component/Validation/ValidatesWhenResolvedTrait.php',


//    $basePath.'/vendor/royalcms/hashing/Royalcms/Component/Hashing/HashServiceProvider.php',
//    $basePath.'/vendor/royalcms/hashing/Royalcms/Component/Hashing/BcryptHasher.php',

//    //pagination
//    $basePath.'/vendor/royalcms/pagination/Royalcms/Component/Pagination/AbstractPaginator.php',
//    $basePath.'/vendor/royalcms/pagination/Royalcms/Component/Pagination/Paginator.php',
//    $basePath.'/vendor/royalcms/pagination/Royalcms/Component/Pagination/PaginationServiceProvider.php',

//    //config
//    $basePath.'/vendor/royalcms/config/Royalcms/Component/Config/FileLoader.php',
//    $basePath.'/vendor/royalcms/config/Royalcms/Component/Config/Repository.php',
//    $basePath.'/vendor/royalcms/config/Royalcms/Component/Config/LoaderInterface.php',
//    $basePath.'/vendor/royalcms/config/Royalcms/Component/Config/EnvironmentVariablesLoaderInterface.php',
//    $basePath.'/vendor/royalcms/config/Royalcms/Component/Config/FileEnvironmentVariablesLoader.php',
//    $basePath.'/vendor/royalcms/config/Royalcms/Component/Config/EnvironmentVariables.php',
//    $basePath.'/vendor/royalcms/config/Royalcms/Component/Config/Dotenv.php',
//    $basePath.'/vendor/royalcms/config/Royalcms/Component/Config/CompatibleTrait.php',

//    //filesystem
//    $basePath.'/vendor/royalcms/filesystem/Royalcms/Component/Filesystem/FileHelperTrait.php',
//    $basePath.'/vendor/royalcms/filesystem/Royalcms/Component/Filesystem/FilesystemAdapter.php',
//    $basePath.'/vendor/royalcms/filesystem/Royalcms/Component/Filesystem/Filesystem.php',
//    $basePath.'/vendor/royalcms/filesystem/Royalcms/Component/Filesystem/FilesystemManager.php',
//    $basePath.'/vendor/royalcms/filesystem/Royalcms/Component/Filesystem/FilesystemServiceProvider.php',

//    //routing
//    $basePath.'/vendor/royalcms/routing/Royalcms/Component/Routing/RoutingServiceProvider.php',
//    $basePath.'/vendor/royalcms/routing/Royalcms/Component/Routing/ControllerServiceProvider.php',
//    $basePath.'/vendor/royalcms/routing/Royalcms/Component/Routing/RouteDependencyResolverTrait.php',
//    $basePath.'/vendor/royalcms/routing/Royalcms/Component/Routing/Route.php',
//    $basePath.'/vendor/royalcms/routing/Royalcms/Component/Routing/Router.php',
//    $basePath.'/vendor/royalcms/routing/Royalcms/Component/Routing/Redirector.php',
//    $basePath.'/vendor/royalcms/routing/Royalcms/Component/Routing/ResponseFactory.php',
//    $basePath.'/vendor/royalcms/routing/Royalcms/Component/Routing/RouteCollection.php',
//    $basePath.'/vendor/royalcms/routing/Royalcms/Component/Routing/Controller.php',
//    $basePath.'/vendor/royalcms/routing/Royalcms/Component/Routing/ControllerDispatcher.php',
//    $basePath.'/vendor/royalcms/routing/Royalcms/Component/Routing/ControllerInspector.php',
//    $basePath.'/vendor/royalcms/routing/Royalcms/Component/Routing/UrlGenerator.php',
//    $basePath.'/vendor/royalcms/routing/Royalcms/Component/Routing/Matching/ValidatorInterface.php',
//    $basePath.'/vendor/royalcms/routing/Royalcms/Component/Routing/Matching/HostValidator.php',
//    $basePath.'/vendor/royalcms/routing/Royalcms/Component/Routing/Matching/MethodValidator.php',
//    $basePath.'/vendor/royalcms/routing/Royalcms/Component/Routing/Matching/SchemeValidator.php',
//    $basePath.'/vendor/royalcms/routing/Royalcms/Component/Routing/Matching/UriValidator.php',

//    //database
//    $basePath.'/vendor/royalcms/database/Royalcms/Component/Database/Query/Builder.php',
//    $basePath.'/vendor/royalcms/database/Royalcms/Component/Database/Eloquent/Builder.php',
//    $basePath.'/vendor/royalcms/database/Royalcms/Component/Database/Eloquent/Collection.php',

//    //bus
//    $basePath.'/vendor/royalcms/bus/Royalcms/Component/Bus/BusServiceProvider.php',
//    $basePath.'/vendor/royalcms/bus/Royalcms/Component/Bus/Dispatcher.php',
//
//    $basePath.'/vendor/royalcms/pipeline/Royalcms/Component/Pipeline/Pipeline.php',

//    //events
//    $basePath.'/vendor/royalcms/events/Royalcms/Component/Events/Dispatcher.php',
//    $basePath.'/vendor/royalcms/events/Royalcms/Component/Events/EventServiceProvider.php',

//    //session
//    $basePath.'/vendor/royalcms/session/Royalcms/Component/Session/SessionInterface.php',
//    $basePath.'/vendor/royalcms/session/Royalcms/Component/Session/StoreInterface.php',
//    $basePath.'/vendor/royalcms/session/Royalcms/Component/Session/Middleware/StartSession.php',
//    $basePath.'/vendor/royalcms/session/Royalcms/Component/Session/Store.php',
//    $basePath.'/vendor/royalcms/session/Royalcms/Component/Session/SessionManager.php',
//    $basePath.'/vendor/royalcms/session/Royalcms/Component/Session/SessionServiceProvider.php',

//    //cookie
//    $basePath.'/vendor/royalcms/cookie/Royalcms/Component/Cookie/CookieJar.php',
//    $basePath.'/vendor/royalcms/cookie/Royalcms/Component/Cookie/Middleware/EncryptCookies.php',
//    $basePath.'/vendor/royalcms/cookie/Royalcms/Component/Cookie/Middleware/AddQueuedCookiesToResponse.php',
//    $basePath.'/vendor/royalcms/cookie/Royalcms/Component/Cookie/CookieServiceProvider.php',

//    //cache
//    $basePath.'/vendor/royalcms/cache/Royalcms/Component/Cache/CacheServiceProvider.php',
//    $basePath.'/vendor/royalcms/cache/Royalcms/Component/Cache/CacheManager.php',
//    $basePath.'/vendor/royalcms/cache/Royalcms/Component/Cache/FileStore.php',
//    $basePath.'/vendor/royalcms/cache/Royalcms/Component/Cache/Repository.php',

//    $basePath.'/vendor/royalcms/encryption/Royalcms/Component/Encryption/BaseEncrypter.php',
//    $basePath.'/vendor/royalcms/encryption/Royalcms/Component/Encryption/Encrypter.php',
//    $basePath.'/vendor/royalcms/encryption/Royalcms/Component/Encryption/EncryptionServiceProvider.php',

//    //log
//    $basePath.'/vendor/royalcms/log/Royalcms/Component/Log/Writer.php',
//    $basePath.'/vendor/royalcms/log/Royalcms/Component/Log/LogServiceProvider.php',
//    $basePath.'/vendor/royalcms/log/Royalcms/Component/Log/FileStore.php',

//    //view
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Middleware/ShareErrorsFromSession.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Engines/EngineResolver.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Engines/Engine.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Engines/PhpEngine.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Engines/FileEngine.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Engines/CompilerEngine.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Concerns/ManagesComponents.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Concerns/ManagesEvents.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Concerns/ManagesLayouts.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Concerns/ManagesLoops.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Concerns/ManagesStacks.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Concerns/ManagesTranslations.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Compilers/CompilerInterface.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Compilers/Compiler.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Compilers/BladeCompiler.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Compilers/Concerns/CompilesAuthorizations.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Compilers/Concerns/CompilesComments.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Compilers/Concerns/CompilesComponents.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Compilers/Concerns/CompilesConditionals.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Compilers/Concerns/CompilesEchos.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Compilers/Concerns/CompilesHelpers.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Compilers/Concerns/CompilesIncludes.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Compilers/Concerns/CompilesInjections.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Compilers/Concerns/CompilesJson.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Compilers/Concerns/CompilesLayouts.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Compilers/Concerns/CompilesLoops.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Compilers/Concerns/CompilesRawPhp.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Compilers/Concerns/CompilesStacks.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Compilers/Concerns/CompilesTranslations.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/ViewFinderInterface.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/FileViewFinder.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/Factory.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/View.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/ViewName.php',
//    $basePath.'/vendor/royalcms/view/Royalcms/Component/View/ViewServiceProvider.php',


//    //translation
//    $basePath.'/vendor/royalcms/translation/Royalcms/Component/Translation/TranslationServiceProvider.php',
//    $basePath.'/vendor/royalcms/translation/Royalcms/Component/Translation/FileLoader.php',
//    $basePath.'/vendor/royalcms/translation/Royalcms/Component/Translation/LoaderInterface.php',
//    $basePath.'/vendor/royalcms/translation/Royalcms/Component/Translation/Translator.php',
//    $basePath.'/vendor/royalcms/translation/Royalcms/Component/Translation/CompatibleTrait.php',

//    $basePath.'/vendor/royalcms/framework/Royalcms/Component/Redis/RedisServiceProvider.php',

//    $basePath.'/vendor/royalcms/datetime/Royalcms/Component/DateTime/Carbon.php',

//    //console
//    $basePath.'/vendor/royalcms/console/Royalcms/Component/Console/Command.php',





];
